USE SocialNetwork;

INSERT INTO privacy_options(`option`)
VALUES
    ('Only Me'),
    ('Circles'),
    ('Friends'),
    ('Friends of Friends'),
    ('Public');

INSERT INTO users(first_name, middle_name, last_name, email, login, password, hash, activated)
    VALUES
    ('Jacob', NULL, 'Smith', 'jacobsmith@example.com', 'jacobsmith', SHA1('pass'), SHA1('jacobsmith@example.com'), 1),
    ('Jacob', NULL, 'Thomas', 'jacobthomas@example.com', 'jacobthomas', SHA1('pass'), SHA1('jacobthomas@example.com'), 1),
    ('Jacob', NULL, 'Jackson', 'jacobjackson@example.com', 'jacobjackson', SHA1('pass'), SHA1('jacobjackson@example.com'), 1),
    ('Jacob', NULL, 'White', 'jacobwhite@example.com', 'jacobwhite', SHA1('pass'), SHA1('jacobwhite@example.com'), 1),
    ('Jacob', NULL, 'Harris', 'jacobharris@example.com', 'jacobharris', SHA1('pass'), SHA1('jacobharris@example.com'), 1),
    ('John', NULL, 'Smith', 'johnsmith@example.com', 'johnsmith', SHA1('pass'), SHA1('johnsmith@example.com'), 1),
    ('John', NULL, 'Thomas', 'johnthomas@example.com', 'johnthomas', SHA1('pass'), SHA1('johnthomas@example.com'), 1),
    ('John', NULL, 'Jackson', 'johnjackson@example.com', 'johnjackson', SHA1('pass'), SHA1('johnjackson@example.com'), 1),
    ('John', NULL, 'White', 'johnwhite@example.com', 'johnwhite', SHA1('pass'), SHA1('johnwhite@example.com'), 1),
    ('John', NULL, 'Harris', 'johnharris@example.com', 'johnharris', SHA1('pass'), SHA1('johnharris@example.com'), 1),
    ('Michael', NULL, 'Smith', 'michaelsmith@example.com', 'michaelsmith', SHA1('pass'), SHA1('michaelsmith@example.com'), 1),
    ('Michael', NULL, 'Thomas', 'michaelthomas@example.com', 'michaelthomas', SHA1('pass'), SHA1('michaelthomas@example.com'), 1),
    ('Michael', NULL, 'Jackson', 'michaeljackson@example.com', 'michaeljackson', SHA1('pass'), SHA1('michaeljackson@example.com'), 1),
    ('Michael', NULL, 'White', 'michaelwhite@example.com', 'michaelwhite', SHA1('pass'), SHA1('michaelwhite@example.com'), 1),
    ('Michael', NULL, 'Harris', 'michaelharris@example.com', 'michaelharris', SHA1('pass'), SHA1('michaelharris@example.com'), 1),
    ('Alexander', NULL, 'Smith', 'alexandersmith@example.com', 'alexandersmith', SHA1('pass'), SHA1('alexandersmith@example.com'), 1),
    ('Alexander', NULL, 'Thomas', 'alexanderthomas@example.com', 'alexanderthomas', SHA1('pass'), SHA1('alexanderthomas@example.com'), 1),
    ('Alexander', NULL, 'Jackson', 'alexanderjackson@example.com', 'alexanderjackson', SHA1('pass'), SHA1('alexanderjackson@example.com'), 1),
    ('Alexander', NULL, 'White', 'alexanderwhite@example.com', 'alexanderwhite', SHA1('pass'), SHA1('alexanderwhite@example.com'), 1),
    ('Alexander', NULL, 'Harris', 'alexanderharris@example.com', 'alexanderharris', SHA1('pass'), SHA1('alexanderharris@example.com'), 1),
    ('Aiden', NULL, 'Smith', 'aidensmith@example.com', 'aidensmith', SHA1('pass'), SHA1('aidensmith@example.com'), 1),
    ('Aiden', NULL, 'Thomas', 'aidenthomas@example.com', 'aidenthomas', SHA1('pass'), SHA1('aidenthomas@example.com'), 1),
    ('Aiden', NULL, 'Jackson', 'aidenjackson@example.com', 'aidenjackson', SHA1('pass'), SHA1('aidenjackson@example.com'), 1),
    ('Aiden', NULL, 'White', 'aidenwhite@example.com', 'aidenwhite', SHA1('pass'), SHA1('aidenwhite@example.com'), 1),
    ('Aiden', NULL, 'Harris', 'aidenharris@example.com', 'aidenharris', SHA1('pass'), SHA1('aidenharris@example.com'), 1),
    ('Sophia', NULL, 'Smith', 'sophiasmith@example.com', 'sophiasmith', SHA1('pass'), SHA1('sophiasmith@example.com'), 1),
    ('Sophia', NULL, 'Thomas', 'sophiathomas@example.com', 'sophiathomas', SHA1('pass'), SHA1('sophiathomas@example.com'), 1),
    ('Sophia', NULL, 'Jackson', 'sophiajackson@example.com', 'sophiajackson', SHA1('pass'), SHA1('sophiajackson@example.com'), 1),
    ('Sophia', NULL, 'White', 'sophiawhite@example.com', 'sophiawhite', SHA1('pass'), SHA1('sophiawhite@example.com'), 1),
    ('Sophia', NULL, 'Harris', 'sophiaharris@example.com', 'sophiaharris', SHA1('pass'), SHA1('sophiaharris@example.com'), 1),
    ('Abigail', NULL, 'Smith', 'abigailsmith@example.com', 'abigailsmith', SHA1('pass'), SHA1('abigailsmith@example.com'), 1),
    ('Abigail', NULL, 'Thomas', 'abigailthomas@example.com', 'abigailthomas', SHA1('pass'), SHA1('abigailthomas@example.com'), 1),
    ('Abigail', NULL, 'Jackson', 'abigailjackson@example.com', 'abigailjackson', SHA1('pass'), SHA1('abigailjackson@example.com'), 1),
    ('Abigail', NULL, 'White', 'abigailwhite@example.com', 'abigailwhite', SHA1('pass'), SHA1('abigailwhite@example.com'), 1),
    ('Abigail', NULL, 'Harris', 'abigailharris@example.com', 'abigailharris', SHA1('pass'), SHA1('abigailharris@example.com'), 1),
    ('Anna', NULL, 'Smith', 'annasmith@example.com', 'annasmith', SHA1('pass'), SHA1('annasmith@example.com'), 1),
    ('Anna', NULL, 'Thomas', 'annathomas@example.com', 'annathomas', SHA1('pass'), SHA1('annathomas@example.com'), 1),
    ('Anna', NULL, 'Jackson', 'annajackson@example.com', 'annajackson', SHA1('pass'), SHA1('annajackson@example.com'), 1),
    ('Anna', NULL, 'White', 'annawhite@example.com', 'annawhite', SHA1('pass'), SHA1('annawhite@example.com'), 1),
    ('Anna', NULL, 'Harris', 'annaharris@example.com', 'annaharris', SHA1('pass'), SHA1('annaharris@example.com'), 1),
    ('Madison', NULL, 'Smith', 'madisonsmith@example.com', 'madisonsmith', SHA1('pass'), SHA1('madisonsmith@example.com'), 1),
    ('Madison', NULL, 'Thomas', 'madisonthomas@example.com', 'madisonthomas', SHA1('pass'), SHA1('madisonthomas@example.com'), 1),
    ('Madison', NULL, 'Jackson', 'madisonjackson@example.com', 'madisonjackson', SHA1('pass'), SHA1('madisonjackson@example.com'), 1),
    ('Madison', NULL, 'White', 'madisonwhite@example.com', 'madisonwhite', SHA1('pass'), SHA1('madisonwhite@example.com'), 1),
    ('Madison', NULL, 'Harris', 'madisonharris@example.com', 'madisonharris', SHA1('pass'), SHA1('madisonharris@example.com'), 1),
    ('Elizabeth', NULL, 'Smith', 'elizabethsmith@example.com', 'elizabethsmith', SHA1('pass'), SHA1('elizabethsmith@example.com'), 1),
    ('Elizabeth', NULL, 'Thomas', 'elizabeththomas@example.com', 'elizabeththomas', SHA1('pass'), SHA1('elizabeththomas@example.com'), 1),
    ('Elizabeth', NULL, 'Jackson', 'elizabethjackson@example.com', 'elizabethjackson', SHA1('pass'), SHA1('elizabethjackson@example.com'), 1),
    ('Elizabeth', NULL, 'White', 'elizabethwhite@example.com', 'elizabethwhite', SHA1('pass'), SHA1('elizabethwhite@example.com'), 1),
    ('Elizabeth', NULL, 'Harris', 'elizabethharris@example.com', 'elizabethharris', SHA1('pass'), SHA1('elizabethharris@example.com'), 1),
    ('Test', NULL, 'User', 'fake@gmail.com', 'test', SHA1('test'), SHA1('fake@gmail.com1391362036'), 1);

INSERT INTO users(first_name, middle_name, last_name, email, login, password, hash, activated, 
    admin)
VALUES
    ('Site', NULL, 'Admin', 'admin@example.com', 'admin', SHA1('admin'),
        SHA1('admin@example.com1391362036'), 1, 1);
INSERT INTO profile(userId, gender, dob, about, locations, languages)
    VALUES
    (1, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Austria', 'English'),
    (2, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Sweden', 'English'),
    (3, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Finland', 'Portuguese'),
    (4, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Belgium', 'English'),
    (5, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Greece', 'Arabic'),
    (6, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Denmark', 'Hindi'),
    (7, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ireland', 'Mandarin'),
    (8, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Switzerland', 'Mandarin'),
    (9, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'France', 'English'),
    (10, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Greece', 'Spanish'),
    (11, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Spain', 'Arabic'),
    (12, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ukraine', 'English'),
    (13, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ukraine', 'Bengali'),
    (14, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Spain', 'French'),
    (15, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ukraine', 'English'),
    (16, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Russia', 'Bengali'),
    (17, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Switzerland', 'English'),
    (18, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Spain', 'Mandarin'),
    (19, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Belgium', 'Hindi'),
    (20, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Germany', 'Bengali'),
    (21, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Poland', 'Arabic'),
    (22, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Finland', 'Mandarin'),
    (23, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ukraine', 'Russian'),
    (24, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'United Kingdom', 'Portuguese'),
    (25, 'Male', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Spain', 'Bengali'),
    (26, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ireland', 'Bengali'),
    (27, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Denmark', 'Russian'),
    (28, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Netherlands', 'Spanish'),
    (29, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'France', 'English'),
    (30, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ireland', 'French'),
    (31, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Czech', 'Spanish'),
    (32, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ireland', 'Mandarin'),
    (33, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Sweden', 'Arabic'),
    (34, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Hungary', 'English'),
    (35, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Spain', 'Portuguese'),
    (36, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Portugal', 'Arabic'),
    (37, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Greece', 'Arabic'),
    (38, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'United Kingdom', 'Hindi'),
    (39, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'United Kingdom', 'Mandarin'),
    (40, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Denmark', 'Spanish'),
    (41, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Germany', 'Bengali'),
    (42, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Denmark', 'Hindi'),
    (43, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Switzerland', 'Russian'),
    (44, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Switzerland', 'English'),
    (45, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Denmark', 'Russian'),
    (46, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Ireland', 'Arabic'),
    (47, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Switzerland', 'Bengali'),
    (48, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Spain', 'Mandarin'),
    (49, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Austria', 'Arabic'),
    (50, 'Female', 593136000, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget laoreet ante. Curabitur posuere mauris et commodo consectetur. Nullam justo est, sodales nec viverra non, faucibus non enim. Donec fringilla eleifend fringilla. Curabitur vestibulum, ipsum et ultrices pulvinar, nulla mi tempor sapien, et eleifend odio nisl a elit. Morbi accumsan dignissim malesuada. Duis malesuada accumsan nunc, egestas tincidunt orci bibendum id. Proin nisi lacus, venenatis at nisl a, convallis euismod lectus. Pellentesque pellentesque lacinia justo id rutrum. Nam lobortis metus sagittis elit tincidunt, at venenatis nisl viverra. In sit amet sem dapibus, eleifend justo a, scelerisque felis.', 'Greece', 'Bengali'),
    (51, 'Female', 593106000, 'A young woman studying in Cambridge', 'England', 'English'),
    (52, 'Male', 593106000, 'I made this site', 'England', 'English');

INSERT INTO friendships(user1, user2, status, startTimestamp)
    VALUES
    (1, 6, 1, 1391362436),
    (1, 9, 1, 1391362436),
    (1, 10, 1, 1391362436),
    (1, 13, 1, 1391362436),
    (1, 14, 0, 1391362436),
    (1, 18, 1, 1391362436),
    (1, 21, 0, 1391362436),
    (1, 23, 0, 1391362436),
    (1, 24, 0, 1391362436),
    (1, 36, 1, 1391362436),
    (1, 44, 1, 1391362436),
    (1, 46, 0, 1391362436),
    (1, 50, 0, 1391362436),
    (1, 51, 0, 1391362436),
    (2, 4, 1, 1391362436),
    (2, 6, 1, 1391362436),
    (2, 11, 1, 1391362436),
    (2, 13, 1, 1391362436),
    (2, 17, 0, 1391362436),
    (2, 24, 1, 1391362436),
    (2, 48, 1, 1391362436),
    (3, 7, 1, 1391362436),
    (3, 11, 1, 1391362436),
    (3, 21, 1, 1391362436),
    (3, 41, 1, 1391362436),
    (3, 43, 1, 1391362436),
    (3, 51, 1, 1391362436),
    (4, 5, 1, 1391362436),
    (4, 7, 1, 1391362436),
    (4, 16, 0, 1391362436),
    (4, 18, 1, 1391362436),
    (4, 21, 1, 1391362436),
    (4, 23, 0, 1391362436),
    (4, 25, 1, 1391362436),
    (4, 28, 1, 1391362436),
    (4, 37, 0, 1391362436),
    (4, 38, 1, 1391362436),
    (4, 39, 1, 1391362436),
    (4, 40, 0, 1391362436),
    (5, 17, 1, 1391362436),
    (5, 18, 1, 1391362436),
    (5, 19, 0, 1391362436),
    (5, 24, 1, 1391362436),
    (5, 37, 1, 1391362436),
    (5, 39, 1, 1391362436),
    (5, 44, 1, 1391362436),
    (5, 51, 1, 1391362436),
    (6, 8, 1, 1391362436),
    (6, 10, 0, 1391362436),
    (6, 15, 1, 1391362436),
    (6, 20, 1, 1391362436),
    (6, 25, 1, 1391362436),
    (6, 46, 1, 1391362436),
    (7, 10, 1, 1391362436),
    (7, 16, 1, 1391362436),
    (7, 18, 1, 1391362436),
    (7, 19, 1, 1391362436),
    (7, 26, 1, 1391362436),
    (7, 29, 1, 1391362436),
    (7, 33, 1, 1391362436),
    (7, 34, 1, 1391362436),
    (7, 36, 1, 1391362436),
    (7, 46, 1, 1391362436),
    (8, 14, 1, 1391362436),
    (8, 15, 1, 1391362436),
    (8, 19, 1, 1391362436),
    (8, 28, 1, 1391362436),
    (8, 29, 1, 1391362436),
    (8, 37, 1, 1391362436),
    (8, 46, 1, 1391362436),
    (8, 47, 1, 1391362436),
    (9, 10, 1, 1391362436),
    (9, 15, 1, 1391362436),
    (9, 22, 1, 1391362436),
    (9, 25, 1, 1391362436),
    (9, 29, 0, 1391362436),
    (9, 35, 1, 1391362436),
    (9, 44, 1, 1391362436),
    (9, 50, 1, 1391362436),
    (10, 12, 1, 1391362436),
    (10, 15, 1, 1391362436),
    (10, 19, 1, 1391362436),
    (10, 30, 1, 1391362436),
    (10, 31, 1, 1391362436),
    (10, 32, 1, 1391362436),
    (10, 34, 1, 1391362436),
    (10, 36, 1, 1391362436),
    (10, 39, 1, 1391362436),
    (10, 42, 1, 1391362436),
    (10, 48, 1, 1391362436),
    (10, 51, 1, 1391362436),
    (11, 12, 1, 1391362436),
    (11, 21, 1, 1391362436),
    (11, 24, 1, 1391362436),
    (11, 25, 0, 1391362436),
    (11, 27, 1, 1391362436),
    (11, 28, 0, 1391362436),
    (11, 29, 1, 1391362436),
    (11, 37, 1, 1391362436),
    (11, 38, 0, 1391362436),
    (11, 51, 1, 1391362436),
    (12, 14, 1, 1391362436),
    (12, 17, 1, 1391362436),
    (12, 38, 1, 1391362436),
    (12, 43, 1, 1391362436),
    (12, 44, 1, 1391362436),
    (12, 49, 1, 1391362436),
    (13, 14, 1, 1391362436),
    (13, 21, 1, 1391362436),
    (13, 26, 1, 1391362436),
    (13, 30, 1, 1391362436),
    (13, 32, 1, 1391362436),
    (13, 37, 1, 1391362436),
    (13, 40, 1, 1391362436),
    (14, 16, 1, 1391362436),
    (14, 21, 1, 1391362436),
    (14, 27, 1, 1391362436),
    (14, 31, 1, 1391362436),
    (14, 35, 0, 1391362436),
    (14, 37, 1, 1391362436),
    (14, 38, 1, 1391362436),
    (14, 47, 1, 1391362436),
    (15, 16, 1, 1391362436),
    (15, 17, 1, 1391362436),
    (15, 27, 1, 1391362436),
    (15, 34, 1, 1391362436),
    (15, 38, 1, 1391362436),
    (15, 39, 1, 1391362436),
    (15, 40, 0, 1391362436),
    (15, 49, 1, 1391362436),
    (15, 50, 0, 1391362436),
    (16, 19, 1, 1391362436),
    (16, 22, 1, 1391362436),
    (16, 26, 1, 1391362436),
    (16, 35, 1, 1391362436),
    (16, 36, 1, 1391362436),
    (16, 39, 1, 1391362436),
    (16, 40, 1, 1391362436),
    (16, 46, 1, 1391362436),
    (17, 22, 1, 1391362436),
    (17, 27, 1, 1391362436),
    (17, 36, 1, 1391362436),
    (17, 41, 1, 1391362436),
    (17, 44, 1, 1391362436),
    (18, 19, 1, 1391362436),
    (18, 24, 1, 1391362436),
    (18, 25, 1, 1391362436),
    (18, 33, 1, 1391362436),
    (18, 37, 1, 1391362436),
    (18, 43, 1, 1391362436),
    (18, 47, 1, 1391362436),
    (19, 47, 1, 1391362436),
    (19, 51, 1, 1391362436),
    (20, 24, 1, 1391362436),
    (20, 26, 1, 1391362436),
    (20, 27, 1, 1391362436),
    (20, 31, 1, 1391362436),
    (20, 33, 1, 1391362436),
    (20, 34, 1, 1391362436),
    (20, 42, 0, 1391362436),
    (20, 43, 1, 1391362436),
    (20, 47, 1, 1391362436),
    (20, 48, 1, 1391362436),
    (20, 50, 1, 1391362436),
    (21, 26, 1, 1391362436),
    (21, 30, 0, 1391362436),
    (21, 32, 0, 1391362436),
    (21, 34, 1, 1391362436),
    (21, 39, 0, 1391362436),
    (21, 40, 1, 1391362436),
    (21, 49, 1, 1391362436),
    (21, 50, 1, 1391362436),
    (22, 25, 1, 1391362436),
    (22, 28, 1, 1391362436),
    (22, 31, 1, 1391362436),
    (22, 34, 1, 1391362436),
    (22, 48, 1, 1391362436),
    (23, 28, 1, 1391362436),
    (23, 29, 1, 1391362436),
    (23, 31, 1, 1391362436),
    (23, 34, 1, 1391362436),
    (23, 35, 1, 1391362436),
    (23, 38, 0, 1391362436),
    (23, 39, 1, 1391362436),
    (23, 40, 1, 1391362436),
    (23, 45, 1, 1391362436),
    (23, 47, 0, 1391362436),
    (24, 39, 0, 1391362436),
    (24, 46, 1, 1391362436),
    (24, 48, 1, 1391362436),
    (25, 28, 1, 1391362436),
    (25, 34, 1, 1391362436),
    (25, 37, 1, 1391362436),
    (25, 38, 1, 1391362436),
    (25, 39, 0, 1391362436),
    (25, 42, 1, 1391362436),
    (26, 35, 1, 1391362436),
    (26, 41, 1, 1391362436),
    (27, 50, 1, 1391362436),
    (28, 37, 0, 1391362436),
    (28, 44, 1, 1391362436),
    (29, 30, 1, 1391362436),
    (29, 31, 0, 1391362436),
    (29, 33, 1, 1391362436),
    (29, 41, 1, 1391362436),
    (29, 42, 0, 1391362436),
    (30, 39, 0, 1391362436),
    (30, 46, 1, 1391362436),
    (30, 47, 0, 1391362436),
    (30, 49, 1, 1391362436),
    (31, 44, 1, 1391362436),
    (31, 45, 1, 1391362436),
    (32, 35, 1, 1391362436),
    (32, 38, 1, 1391362436),
    (32, 40, 1, 1391362436),
    (32, 43, 1, 1391362436),
    (33, 35, 0, 1391362436),
    (34, 37, 1, 1391362436),
    (34, 41, 1, 1391362436),
    (34, 45, 1, 1391362436),
    (35, 36, 0, 1391362436),
    (35, 37, 0, 1391362436),
    (35, 42, 1, 1391362436),
    (35, 44, 1, 1391362436),
    (35, 45, 1, 1391362436),
    (35, 47, 1, 1391362436),
    (35, 51, 1, 1391362436),
    (36, 37, 1, 1391362436),
    (36, 39, 0, 1391362436),
    (36, 44, 1, 1391362436),
    (36, 50, 0, 1391362436),
    (37, 45, 1, 1391362436),
    (37, 46, 0, 1391362436),
    (37, 47, 1, 1391362436),
    (38, 40, 1, 1391362436),
    (38, 41, 0, 1391362436),
    (38, 48, 1, 1391362436),
    (39, 41, 1, 1391362436),
    (39, 42, 0, 1391362436),
    (40, 48, 0, 1391362436),
    (41, 47, 0, 1391362436),
    (41, 50, 1, 1391362436),
    (43, 44, 0, 1391362436),
    (43, 46, 0, 1391362436),
    (43, 51, 1, 1391362436),
    (44, 49, 1, 1391362436),
    (45, 46, 1, 1391362436),
    (45, 50, 1, 1391362436),
    (46, 47, 0, 1391362436),
    (46, 48, 1, 1391362436),
    (47, 51, 1, 1391362436),
    (48, 51, 1, 1391362436),
    (49, 50, 0, 1391362436),
    (50, 51, 1, 1391362436);


INSERT INTO circles(owner, name)
VALUES
    (51, 'Work'),
    (51, 'Family');

INSERT INTO circle_memberships(user, circle)
VALUES
    (48, 1),
    (1, 1),
    (3, 1),
    (5, 2),
    (10, 1),
    (50, 1),
    (43, 2);

INSERT INTO messages(`from`, `to_user`, `to_circle`, `type`, `content`, `timestamp`)
VALUES
    (51, 48, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (51, 48, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (51, 10, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (10, 51, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (51, 10, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (10, 51, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (51, 10, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (3, 51, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (5, 51, NULL, 'P', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (51, NULL, 1, 'C', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436),
    (51, NULL, 1, 'C', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436);

INSERT INTO blogs(`user`, `name`, `url`, `about`, `privacy`)
VALUES 
    (51, 'Cooking', 'cooking', 'A simple cooking blog.', 3),
    (51, 'Personal', 'personal', 'My personal life :)', 1);

INSERT INTO posts(`blogId`, `title`, `timestamp`)
VALUES
    (1, 'Bok Choy', 1393003907),
    (1, 'Chicken stir-fry', 1361454065),
    (1, 'Dessert', 1361536865),
    (1, 'Chocolate trifle', 1362055265),
    (1, 'Beef Burger', 1363869665),
    (1, 'Chicken Burger', 1366548065),
    (1, 'Salsa', 1366551665),
    (1, 'Home-made pasta', 1366634465);

INSERT INTO posts_details(`postId`, `content`)
VALUES 
    (1, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"),
    (2, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"),
    (3, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"),
    (4, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"),
    (5, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"),
    (6, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"),
    (7, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"),
    (8, "<p><a href=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock.png\" rel=\"prettyPhoto[42]\"><img class=\"alignleft\" title=\"1311022937_lock\" src=\"http://themes.simplethemes.com/orion/wp-content/uploads/2011/07/1311022937_lock-150x150.png\" alt=\"\" width=\"150\" height=\"150\" /></a>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<br />
        <span id=\"more-42\"></span><br />
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#8217;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>");

INSERT INTO photo_albums(`user`, `name`, `about`, `privacy`)
VALUES 
    (51, 'Summer Holidays', 'My summer Holidays.', 3),
    (51, 'Cuba', 'Had a great time in Cuba :P', 3);


INSERT INTO photos(`albumId`, `timestamp`, `description`, `url`, `thumbnailUrl`)
VALUES 
    (1, 1394135655, 'A nice description', '/uploads/album_pics/full/31394135655.jpg', 
        '/uploads/album_pics/thumbnail/31394135655.jpg'),
    (1, 1394135578, null, '/uploads/album_pics/full/31394135578.jpg', 
        '/uploads/album_pics/thumbnail/31394135578.jpg');

INSERT INTO wall_posts(`to`, `from`, `content`, `timestamp`, `type`, `lastTouched`)
VALUES
    (51, 51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362436, 'post', 1391362436),
    (51, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362536, 'post', 1391362436),
    (51, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362636, 'post', 1391362436),
    (51, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362736, 'post', 1391362436),
    (51, 51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391368436, 'post', 1391362436),
    (51, 51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362936, 'post', 1391362436),
    (51, 51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1391362996, 'post', 1391362436);

